config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resource :comment,  only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :user_id, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create, :destroy]

  def create
    Comment.create(post: @post, user: @user, body: @body) if valid_request?
    redirect_to_post
  end

  def destroy
    Comment.find_by(id: params[:comment_id])&.destroy
    redirect_to_post
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to post_path and return
  end

  def valid_request?
    @post.present? && valid_user? && valid_body?
  end

  def valid_user?
    @user = User.find_by(email: params[:user_email].strip.downcase)
    @user.present?.tap do |valid_user|
      flash[:error] = "You must provide an email address for a user that exists." unless valid_user
    end
  end

  def valid_body?
    @body = params[:body]
    @body.present?.tap do |valid_body|
      flash[:error] = "You cannot submit a comment without a body." unless valid_body
    end
  end

  def redirect_to_post
    redirect_to post_path(@post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc).take(10)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    user_email = params[:post][:user_email].strip.downcase
    user = User.find_by(email: user_email)
    if user.blank?
      flash.now[:error] = "You must provide an email address for a user that exists."
      @post = Post.new
      render :new and return
    end

    body = params[:post][:body]

    if body.empty?
      flash.now[:error] = "You cannot submit a post without a body."
      @post = Post.new
      render :new and return
    end

    @post = Post.new(user_id: user.id, body: body, active: true)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
  end

  def update
    body = params[:post][:body]

    if body.empty?
      flash.now[:error] = "You cannot submit a post without a body."
      render :edit and return
    end

    if @post.update(body: body)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, notice: "That post could not be found"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_img_url(email)
        standardized_email = email.strip.downcase
        gravatar_hash = Digest::MD5.hexdigest standardized_email
        default_theme = 'retro'
        size = 64
        "https://www.gravatar.com/avatar/#{gravatar_hash}?s=#{size}&d=#{default_theme}"
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def comment_preview_limit
        3
    end

    def excess_comment_count(post)
        post.comments.count - comment_preview_limit
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogusBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top custom-font">
      <div class="container">
        <div class="navbar-header">
          <a href="<%= posts_path %>" class="navbar-brand">Bogus Board</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "New post", controller: "posts", action: "new" %></li>
        </ul>
      </div>
    </nav>

    <div id="body-spacer"></div>

    <div id="main-content" class="container">
      <% flash.each do |_, flash_message| %>
        <div class="alert alert-info"><%= flash_message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Edit Post</h2>
    </div>
    <div class="panel-body">
        <%= form_with(model: @post) do |form| %>
            <div class="form-group">
                <label for="author_name">Author</label>
                <div id="author_name"><%= @post.user.display_name %></div>
            </div>
            <div class="form-group">
                <%= form.label :body %>
                <%= form.text_area :body, class: 'form-control' %>
            </div>
            <%= form.submit "Update Post", class: 'btn btn-default' %>
        <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<% if @posts and @posts.any? %>
    <h1>Recent Posts</h1>

    <% @posts.each do |post| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="media">
                    <div class="media-left">
                        <a href="<%= post_path(post.id) %>">
                            <img src="<%= gravatar_img_url(post.user.email) %>">
                        </a>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading"><%= post.body %></h3>
                    </div>
                    <div class="media-right">
                        <%= link_to "Add Comment / Edit", post_path(post.id), class: 'btn btn-primary btn-sm' %>
                    </div>
                </div>
            </div>
            <div class="panel-body comment-list">
                <% if post.comments.count == 0 %>
                    <span>This post does not have any comments yet.</span>
                <% else %>
                    <% post.comments.order(created_at: :desc).limit(comment_preview_limit).each do |comment| %>
                        <div class="media">
                            <div class="media-left">
                                <img src="<%= gravatar_img_url(comment.user.email) %>">
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><%= comment.body %></h4>
                                <em>Submitted by <%= comment.user.display_name %> at <%= comment.created_at %></em>
                            </div>
                        </div>
                    <% end %>
                    <% if post.comments.count > comment_preview_limit %>
                        <br />
                        <span>(<%= excess_comment_count(post) %> more <%= 'comment'.pluralize(excess_comment_count(post)) %>)</span>
                        <%= link_to "view full thread", post_path(post.id) %>
                    <% end %>
                <% end %>
            </div>
            <div class="panel-footer">
                <%= post.user.display_name %> created post at <%= post.created_at %>
                <% if post.updated_at > post.created_at %>
                    <div class="pull-right">
                        Last edited <%= time_ago_in_words(post.updated_at) %> ago
                    </div>
                <% end %>
            </div>
        </div>
    <% end %>
<% else %>
    <h2>It seem that there are no posts yet. Please feel free to get things started by using the button in the menu bar.</h2>
<% end %>

app/views/posts/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>New Post</h2>
    </div>
    <div class="panel-body">
        <%= form_with(model: @post) do |form| %>
            <div class="form-group">
                <%= form.label :user_email %>
                <%= form.text_field :user_email, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= form.label :body %>
                <%= form.text_area :body, class: 'form-control' %>
            </div>
            <%= form.submit "Create Post", class: 'btn btn-default' %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <h2>
            <img src="<%= gravatar_img_url(@post.user.email) %>">
            <%= @post.body %>
        </h2>
    </div>
    <div class="panel-footer">
        <%= @post.user.display_name %> created post at <%= @post.created_at %>
        <% if @post.updated_at > @post.created_at %>
            <div class="pull-right">
                Last edited <%= time_ago_in_words(@post.updated_at) %> ago
            </div>
        <% end %>
    </div>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %>
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

<hr>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Add a comment</h4>
    </div>
    <div class="panel-body">
        <%= form_with url: comment_path, method: :post do |form|  %>
            <%= form.hidden_field :post_id, value: @post.id %>
            <div class="form-group">
                <%= form.label :user_email %>
                <%= form.text_field :user_email, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= form.label :body %>
                <%= form.text_area :body, class: 'form-control' %>
            </div>
            <%= form.submit "Add Comment", class: 'btn btn-default' %>
        <% end %>
    </div>
</div>
<hr>

<% if @post.comments.count > 0 %>
    <h3>Comments</h3>

    <ul class="list-group">
        <% @post.comments.order(created_at: :asc).each do |comment| %>
            <li class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="<%= gravatar_img_url(comment.user.email) %>">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><%= comment.body %></h4>
                        <em>Submitted by <%= comment.user.display_name %> at <%= comment.created_at %></em>
                    </div>
                    <div class="media-right">
                        <%= form_with url: comment_path, method: :delete do |form|  %>
                            <%= form.hidden_field :post_id, value: @post.id %>
                            <%= form.hidden_field :comment_id, value: comment.id %>
                            <%= form.submit "Delete", class: 'btn btn-danger' %>
                        <% end %>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
<% else %>
    <h4>This post has no comments.</h4>
<% end %>